# This experiment was done by training on the whole training set.
# All the features, but normalized to zero mean and unit variance.
# Regularized logistic regression.
# Cross validation.
# 3 degree polynomial features
# Accuracy 0.75 and F1 score 0.622 on the test set.

# Parameters

# step_size
gamma: 0.4
# number of steps to run
max_iters: 5000
# regularization parameter
lambda: 0.05
# ratio split
ratio: null
# Enable cross validation
cross_val: True
# Number of folds for cross-validation
kfold: 5
# Whether to build polynomial features or not
build_poly: True
# Degrees for polynomial features
degree: 3

# Paths
train_data: "../data/train.csv"
test_data: "../data/test.csv"
# Submissions output_path
output_path: "../results/"
# Visualizations output path
viz_path: "../visualizations/"