# COMPARABLE WITH EXPERIMENT 3, WITH FEATURE SCALING CHANGED TO NORMALIZE

# This experiment was done by training on the whole training set.
# All the features + 2 degree polynomial, but normalized.
# Training accuracy is 0.707, so test was not run !


# Parameters

# step_size
gamma: 0.5
# number of steps to run
max_iters: 5000
# regularization parameter
lambda: null
# ratio split
ratio: null
# Enable cross validation
cross_val: False
# Number of folds for cross-validation
kfold: null
# Whether to build polynomial features or not
build_poly: True
# Degrees for polynomial features
degree: 2
# Wheather to multiply each column with each column and expand features
multiply_each: False
# Replace -999 values with specified value, this can take 'zero', 'mean' or null
replace_with: null
# Apply only normalization
only_normalize: True


# Paths
train_data: "../data/train.csv"
test_data: "../data/test.csv"
# Submissions output_path
output_path: "../results/"
# Visualizations output path
viz_path: "../visualizations/"