# DO NOT CHANGE THIS BECAUSE THIS IS THE CONFIG FOR THE 19TH EXPERIMENT (COMPARABLE WITH 16), BUILD ANOTHER ONE

# This experiment was done by training on the whole training set.
# All the features + 6 degree polynomial and SQUARE ROOT features, but standardized to zero mean and unit variance. # Degree 6 does not seem to help !!!!
# Replaced all -999 values with feature-wise median !!!.
# Max_iters was increased to 10000.
# Cross validation was run.
# Removed outliers at training, before replacing values of -999.
# Regularized log reg with lambda=1.
# Accuracy 0.794 and F1 score 0.679 on the test set. - SO 6 DEGREES ARE WORSE THAN 3


# Parameters

# Model type
model: reg_log
# step_size
gamma: 0.5
# number of steps to run
max_iters: 10000
# regularization parameter
lambda: 1
# ratio split
ratio: null
# Enable cross validation
cross_val: True
# Number of folds for cross-validation
kfold: 5
# Whether to build polynomial features or not
build_poly: True
# Degrees for polynomial features
degree: 6
# Wheather to multiply each column with each column and expand features
multiply_each: False
# Take square root of features
square_root: True
# Apply log transform as scaler
log_transform: False
# Replace -999 values with specified value, this can take 'zero', 'mean', 'median', 'mode' or null
replace_with: 'median'
# Apply only normalization
only_normalize: False
# Logistic regression threshold
reg_threshold: 0.05
# remove ouliers:
remove_outliers: 'std'
# Drop correlated features
drop_corr: False
# Expand angle features by taking cos and sin
trig: False

# Paths
train_data: "../data/train.csv"
test_data: "../data/test.csv"
# Submissions output_path
output_path: "../results/"
# Visualizations output path
viz_path: "../visualizations/"