# DO NOT CHANGE THIS BECAUSE THIS IS THE CONFIG FOR THE SECOND EXPERIMENT, BUILD ANOTHER ONE

# This experiment was done by training on the whole training set.
# All the features, but standardized to zero mean and unit variance.
# Cross-validation.
# Regularized logistic regression.
# Accuracy 0.75 and F1 score 0.622 on the test set.

# Parameters

# step_size
gamma: 0.4
# number of steps to run
max_iters: 6000
# regularization parameter
lambda: 0.05
# ratio split
ratio: null
# Enable cross validation
cross_val: False
# Number of folds for cross-validation
kfold: null
# Whether to build polynomial features or not
build_poly: False
# Degrees for polynomial features
degree: null
# Wheather to multiply each column with each column and expand features
multiply_each: False
# Take square root of features
square_root: False
# Apply log transform as scaler
log_transform: False
# Replace -999 values with specified value, this can take 'zero', 'mean', 'median', 'mode' or null
replace_with: null
# Apply only normalization
only_normalize: False
# Logistic regression threshold
reg_threshold: 0.5
# remove ouliers:
remove_outliers: False

# Paths
train_data: "../data/train.csv"
test_data: "../data/test.csv"
# Submissions output_path
output_path: "../results/"
# Visualizations output path
viz_path: "../visualizations/"