# Parameters for each of the models (by jet number)

# Best results (always the recent configuration)

#Cross validation f1 score is 66.30 % and accuracy is 84.47 %
#Training F1 score is 66.55 % and accuracy is 84.58 %
#
#Cross validation f1 score is 72.09 % and accuracy is 80.65 %
#Training F1 score is 72.40 % and accuracy is 80.87 %
#
#Cross validation f1 score is 81.80 % and accuracy is 83.63 %
#Training F1 score is 82.21 % and accuracy is 84.01 %
#
#Overall validation F1 score is 73.40 % and accuracy is 82.92 %


zero_jet:

  # Model type
  model: ridge
  # step_size
  gamma: null
  # number of steps to run
  max_iters: null
  # regularization parameter
  lambda: 0.00000000001
  # ratio split
  ratio: null
  # Enable cross validation
  cross_val: True
  # Number of folds for cross-validation
  kfold: 5
  # Whether to build polynomial features or not
  build_poly: True
  # Degrees for polynomial features
  degree: 11
  # Wheather to multiply each column with each column and expand features
  multiply_each: True
  # Take square root of features
  square_root: True
  # Apply log transform as scaler
  log_transform: False
  # Replace -999 values with specified value, this can take 'zero', 'mean', 'median', 'mode' or null
  replace_with: 'mode'
  # Apply only normalization
  only_normalize: False
  # Logistic regression threshold
  reg_threshold: 0.5
  # remove outliers:
  remove_outliers: False
  # Drop correlated features
  drop_corr: True

  # Paths
  train_data: "../data/train.csv"
  test_data: "../data/test.csv"
  # Submissions output_path
  output_path: "../results/"
  # Visualizations output path
  viz_path: "../visualizations/"

one_jet:
  # Weaker results for this model:
  # degree 8:
  # Cross validation f1 score is 71.21 % and accuracy is 80.13 %
  # Training F1 score is 71.17 % and accuracy is 80.10 %


  # Model type
  model: ridge
  # step_size
  gamma: null
  # number of steps to run
  max_iters: null
  # regularization parameter
  lambda: 0.0000000001
  # ratio split
  ratio: null
  # Enable cross validation
  cross_val: True
  # Number of folds for cross-validation
  kfold: 5
  # Whether to build polynomial features or not
  build_poly: True
  # Degrees for polynomial features
  degree: 10
  # Wheather to multiply each column with each column and expand features
  multiply_each: True
  # Take square root of features
  square_root: True
  # Apply log transform as scaler
  log_transform: False
  # Replace -999 values with specified value, this can take 'zero', 'mean', 'median', 'mode' or null
  replace_with: 'mode'
  # Apply only normalization
  only_normalize: False
  # Logistic regression threshold
  reg_threshold: 0.5
  # remove outliers:
  remove_outliers: False
  # Drop correlated features
  drop_corr: False

  # Paths
  train_data: "../data/train.csv"
  test_data: "../data/test.csv"
  # Submissions output_path
  output_path: "../results/"
  # Visualizations output path
  viz_path: "../visualizations/"

more_than_one_jet:

  # Model type
  model: ridge
  # step_size
  gamma: null
  # number of steps to run
  max_iters: null
  # regularization parameter
  lambda: 0.0000000001
  # ratio split
  ratio: null
  # Enable cross validation
  cross_val: True
  # Number of folds for cross-validation
  kfold: 5
  # Whether to build polynomial features or not
  build_poly: True
  # Degrees for polynomial features
  degree: 11
  # Wheather to multiply each column with each column and expand features
  multiply_each: True
  # Take square root of features
  square_root: True
  # Apply log transform as scaler
  log_transform: False
  # Replace -999 values with specified value, this can take 'zero', 'mean', 'median', 'mode' or null
  replace_with: 'mode'
  # Apply only normalization
  only_normalize: False
  # Logistic regression threshold
  reg_threshold: 0.5
  # remove outliers:
  remove_outliers: False
  # Drop correlated features
  drop_corr: False

  # Paths
  train_data: "../data/train.csv"
  test_data: "../data/test.csv"
  # Submissions output_path
  output_path: "../results/"
  # Visualizations output path
  viz_path: "../visualizations/"

# Paths
train_data: "../data/train.csv"
test_data: "../data/test.csv"
# Submissions output_path
output_path: "../results/"
# Visualizations output path
viz_path: "../visualizations/"