
# Parameters for each of the models (by jet number)

# Best results (always the recent configuration)

#Cross validation f1 score is 66.65 % and accuracy is 84.63 %
#Training F1 score is 66.87 % and accuracy is 84.73 %
#
#Cross validation f1 score is 72.88 % and accuracy is 81.05 %
#Training F1 score is 73.18 % and accuracy is 81.27 %
#
#Cross validation f1 score is 82.38 % and accuracy is 84.09 %
#Training F1 score is 82.82 % and accuracy is 84.49 %
#
#Overall validation F1 score is 73.97 % and accuracy is 83.26 %

zero_jet:
  # Model type
  model: ridge
  # step_size
  gamma: null
  # number of steps to run
  max_iters: null
  # regularization parameter 1e-15
  lambda: 0.000000000000001
  # ratio split
  ratio: null
  # Enable cross validation
  cross_val: True
  # Number of folds for cross-validation
  kfold: 5
  # Whether to build polynomial features or not
  build_poly: True
  # Degrees for polynomial features
  degree: 10
  # Whether to multiply each column with each column and expand features
  multiply_each: True
  # Take square root of features
  square_root: True
  # Apply log transform as scalar
  log_transform: False
  # Replace -999 values with specified value, this can take 'zero', 'mean', 'median', 'mode' or null
  replace_with: 'median'
  # Apply only normalization
  only_normalize: False
  # Logistic regression threshold
  reg_threshold: 0.5
  # remove outliers:
  remove_outliers: False
  # Drop correlated features
  drop_corr: False
  # Expand angle features by taking cos and sin
  trig: False

  # Paths
  train_data: "../data/train.csv"
  test_data: "../data/test.csv"
  # Submissions output_path
  output_path: "../results/"
  # Visualizations output path
  viz_path: "../visualizations/"

one_jet:
  # Model type
  model: ridge
  # step_size
  gamma: null
  # number of steps to run
  max_iters: null
  # regularization parameter 1e-13
  lambda: 0.0000000000001
  # ratio split
  ratio: null
  # Enable cross validation
  cross_val: True
  # Number of folds for cross-validation
  kfold: 5
  # Whether to build polynomial features or not
  build_poly: True
  # Degrees for polynomial features
  degree: 11
  # Whether to multiply each column with each column and expand features
  multiply_each: True
  # Take square root of features
  square_root: True
  # Apply log transform as scalar
  log_transform: False
  # Replace -999 values with specified value, this can take 'zero', 'mean', 'median', 'mode' or null
  replace_with: 'mode'
  # Apply only normalization
  only_normalize: False
  # Logistic regression threshold
  reg_threshold: 0.5
  # remove outliers:
  remove_outliers: False
  # Drop correlated features
  drop_corr: False
  # Expand angle features by taking cos and sin
  trig: False

  # Paths
  train_data: "../data/train.csv"
  test_data: "../data/test.csv"
  # Submissions output_path
  output_path: "../results/"
  # Visualizations output path
  viz_path: "../visualizations/"

more_than_one_jet:
  # Model type
  model: ridge
  # step_size
  gamma: null
  # number of steps to run
  max_iters: null
  # regularization parameter 1e-16
  lambda: 0.0000000000000001
  # ratio split
  ratio: null
  # Enable cross validation
  cross_val: True
  # Number of folds for cross-validation
  kfold: 5
  # Whether to build polynomial features or not
  build_poly: True
  # Degrees for polynomial features
  degree: 11
  # Whether to multiply each column with each column and expand features
  multiply_each: True
  # Take square root of features
  square_root: True
  # Apply log transform as scalar
  log_transform: False
  # Replace -999 values with specified value, this can take 'zero', 'mean', 'median', 'mode' or null
  replace_with: 'mode'
  # Apply only normalization
  only_normalize: False
  # Logistic regression threshold
  reg_threshold: 0.5
  # remove outliers:
  remove_outliers: False
  # Drop correlated features
  drop_corr: False
  # Expand angle features by taking cos and sin
  trig: False

  # Paths
  train_data: "../data/train.csv"
  test_data: "../data/test.csv"
  # Submissions output_path
  output_path: "../results/"
  # Visualizations output path
  viz_path: "../visualizations/"

# Paths
train_data: "../data/train.csv"
test_data: "../data/test.csv"
# Submissions output_path
output_path: "../results/"
# Visualizations output path
viz_path: "../visualizations/"