# DO NOT CHANGE THIS BECAUSE THIS IS THE CONFIG FOR THE FIFTH EXPERIMENT, BUILD ANOTHER ONE

# This experiment was done by training on the whole training set.
# All the features + 2 degree polynomial, but standardized to zero mean and unit variance.
# Replaced all -999 values with feature-wise mean.
# Accuracy 0.786 and F1 score 0.67 on the test set.

# Parameters

# step_size
gamma: 0.5
# number of steps to run
max_iters: 5000
# regularization parameter
lambda: null
# ratio split
ratio: null
# Enable cross validation
cross_val: False
# Number of folds for cross-validation
kfold: null
# Whether to build polynomial features or not
build_poly: True
# Degrees for polynomial features
degree: 2
# Wheather to multiply each column with each column and expand features
multiply_each: False
# Replace -999 values with specified value, this can take 'zero', 'mean' or null
replace_with: 'mean'

# Paths
train_data: "../data/train.csv"
test_data: "../data/test.csv"
# Submissions output_path
output_path: "../results/"
# Visualizations output path
viz_path: "../visualizations/"