# This experiment was done by training on the whole training set.
# All the features + 3 degree polynomial, but NORMALIZED.
# Replaced all -999 values with feature-wise mean.
# Max_iters was increased to 10000.
# Accuracy ? and F1 score ? on the test set. - Accuracy was 0.728 on training so this was not tested and submitted.

# Parameters

# step_size
gamma: 0.5
# number of steps to run
max_iters: 10000
# regularization parameter
lambda: null
# ratio split
ratio: null
# Enable cross validation
cross_val: False
# Number of folds for cross-validation
kfold: null
# Whether to build polynomial features or not
build_poly: True
# Degrees for polynomial features
degree: 3
# Wheather to multiply each column with each column and expand features
multiply_each: False
# Replace -999 values with specified value, this can take 'zero', 'mean' or null
replace_with: 'mean'
# Apply only normalization
only_normalize: True

# Paths
train_data: "../data/train.csv"
test_data: "../data/test.csv"
# Submissions output_path
output_path: "../results/"
# Visualizations output path
viz_path: "../visualizations/"