# Parameters

# step_size
gamma: 0.5
# number of steps to run
max_iters: 1000
# regularization parameter
lambda: null
# ratio split
ratio: null
# Enable cross validation
cross_val: True
# Number of folds for cross-validation
kfold: 5
# Whether to build polynomial features or not
build_poly: False
# Degrees for polynomial features
degree: null

# Paths
train_data: "../data/train.csv"
test_data: "../data/test.csv"
# Submissions output_path
output_path: "../results/"
# Visualizations output path
viz_path: "../visualizations/"