#Training F1 score is 56.83 % and accuracy is 74.50 %

# Parameters

# Model type
model: ls
# step_size
gamma: null
# number of steps to run
max_iters: null
# regularization parameter
lambda: null
# ratio split
ratio: null
# Enable cross validation
cross_val: False
# Number of folds for cross-validation
kfold: null
# Whether to build polynomial features or not
build_poly: False
# Degrees for polynomial features
degree: null
# Whether to multiply each column with each column and expand features
multiply_each: False
# Take square root of features
square_root: False
# Apply log transform as scalar
log_transform: False
# Replace -999 values with specified value, this can take 'zero', 'mean', 'median', 'mode' or null
replace_with: null
# Apply only normalization
only_normalize: False
# Logistic regression threshold
reg_threshold: 0.5
# remove outliers:
remove_outliers: False
# Drop correlated features
drop_corr: False
# Expand angle features by taking cos and sin
trig: False

# Paths
train_data: "../data/train.csv"
test_data: "../data/test.csv"
# Submissions output_path
output_path: "../results/"
# Visualizations output path
viz_path: "../visualizations/"