"""
# DO NOT CHANGE THIS BECAUSE THIS IS THE CONFIG FOR THE FIRST EXPERIMENT, BUILD ANOTHER ONE
# This experiment was done by training on an arbitrary 80% of the training set and not the whole training set.
# We used split data function for that.
# We used all the features, but normalized to zero mean and unit variance.
# Accuracy 0.75 and F1 score 0.624 on the test set.
"""

# Parameters

# step_size
gamma: 0.5
# number of steps to run
max_iters: 1000
# ratio split
ratio: 0.8
# Enable cross validation
cross_val: False

# Paths
train_data: data/train.csv
test_data: data/test.csv
output_path: submissions/



