# DO NOT CHANGE THIS BECAUSE THIS IS THE CONFIG FOR THE ELEVENTH EXPERIMENT, BUILD ANOTHER ONE

# This experiment was done by training on the whole training set.
# All the features + 3 degree polynomial, but standardized to zero mean and unit variance.
# Replaced all -999 values with feature-wise mean.
# Max_iters was increased to 10000.
# Cross validation was run.
# Removed outliers at training, before replacing values of -999.
# Threshold of 0.05 for logistic regression
# Accuracy 0.805 and F1 score 0.691 on the test set.

# Threshold: 0.4 - 80.92 accuracy at training
#            0.3 - 81.17
#            0.25 - 81.28
#            0.2 - 81.39

# Parameters

# step_size
gamma: 0.5
# number of steps to run
max_iters: 10000
# regularization parameter
lambda: null
# ratio split
ratio: null
# Enable cross validation
cross_val: False
# Number of folds for cross-validation
kfold: null
# Whether to build polynomial features or not
build_poly: True
# Degrees for polynomial features
degree: 3
# Wheather to multiply each column with each column and expand features
multiply_each: False
# Take square root of features
square_root: False
# Apply log transform as scaler
log_transform: False
# Replace -999 values with specified value, this can take 'zero', 'mean', 'median', 'mode' or null
replace_with: 'mean'
# Apply only normalization
only_normalize: False
# Logistic regression threshold
reg_threshold: 0.05
# remove ouliers:
remove_outliers: True

# Paths
train_data: "../data/train.csv"
test_data: "../data/test.csv"
# Submissions output_path
output_path: "../results/"
# Visualizations output path
viz_path: "../visualizations/"