# DO NOT CHANGE THIS BECAUSE THIS IS THE CONFIG FOR THE 20TH EXPERIMENT (COMPARABLE WITH 3), BUILD ANOTHER ONE

# This experiment was done by training on the whole training set.
# All the features + 2 degree polynomial, but standardized to zero mean and unit variance.
# Cross-validation.
# Ridge regression, so need a lambda = 0.0001.

# Validation f1 score is 61.54 %
# Training F1 score is 61.47 % and accuracy is 76.194


# Parameters

# Model type
model: ridge
# step_size
gamma: null
# number of steps to run
max_iters: null
# regularization parameter
lambda: 0.0001
# ratio split
ratio: null
# Enable cross validation
cross_val: True
# Number of folds for cross-validation
kfold: 5
# Whether to build polynomial features or not
build_poly: True
# Degrees for polynomial features
degree: 2
# Whether to multiply each column with each column and expand features
multiply_each: False
# Take square root of features
square_root: False
# Apply log transform as scalar
log_transform: False
# Replace -999 values with specified value, this can take 'zero', 'mean', 'median', 'mode' or null
replace_with: null
# Apply only normalization
only_normalize: False
# Logistic regression threshold
reg_threshold: 0.5
# remove outliers:
remove_outliers: False
# Drop correlated features
drop_corr: False
# Expand angle features by taking cos and sin
trig: False

# Paths
train_data: "../data/train.csv"
test_data: "../data/test.csv"
# Submissions output_path
output_path: "../results/"
# Visualizations output path
viz_path: "../visualizations/"