# Parameters

# step_size
gamma: 0.2
# number of steps to run
max_iters: 5000
# regularization parameter
lambda: 0.01
# ratio split
ratio: 0.8
# Number of folds for cross-validation
kfold: 5

# Paths
train_data: data/train.csv
test_data: data/test.csv
output_path: submissions/