# Parameters

# step_size
gamma: 0.2
# number of steps to run
max_iters: 5000
# regularization parameter
lambda: 0.01

# Paths
train_data: data/train.csv
test_data: data/test.csv
output_path: submissions/



